### ISSUE TITLE
Does not compile in Ubuntu 18.04

### ISSUE THREAD

**Issue by frankalicious** [FreeJoy-Team/FreeJoyConfiguratorQt#15]
```
$ qmake --version
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

$ lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

```
$ qmake FreeJoyQt.pro
$ make
...
centered_cbox.cpp: In member function ‘virtual void CenteredCBox::paintEvent(QPaintEvent*)’:
centered_cbox.cpp:36:36: error: ‘class QFontMetricsF’ has no member named ‘horizontalAdvance’
     qreal font_width = font_metric.horizontalAdvance(option.currentText);// * 1.1f;
```

horizontalAdvance seems to be added with QT 5.11: https://stackoverflow.com/a/51180029

**Comment by Reksotiv** [comment]
thanks, replaced 5.9 with 5.11

**Comment by frankalicious** [comment]
Fixed with bd622cf47a95acf2417e6527c1bbd0ec0bd4108e and bcf8a41270fafd783e1f3f57ba18228be75ff270
